# code:

#Importing required libraries and functions

In [26]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.cross_validation import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import MinMaxScaler

#Importing dataset and feature scaling it using minmax scaler to scale all the values to same range

In [ ]:
df=pd.read_csv('Statistician Dataset.csv')
df=df.astype(float)

In [60]:
sc=MinMaxScaler()
d=sc.fit_transform(df)
df=pd.DataFrame(d,columns=df.columns)

In [61]:
df

x1   x2   x3   x4   x5   x6   x7   x8   x9  x10 ...   x435      x436  \
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.076209   
1    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.016561   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.136808   
3    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.025190   
4    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.030852   
5    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.013182   
6    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.057211   
7    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.029665   
8    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.057183   
9    0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.031149   
10   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.019894   
11   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.043303   
12   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.066178   
13   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
14   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.022935   
15   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.210447   
16   0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.005182   
17   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.049179   
18   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.114102   
19   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
20   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.003502   
21   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.067845   
22   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.091733   
23   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.030057   
24   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.008534   
25   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.004817   
26   0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.050056   
27   1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.000000   
28   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.096788   
29   0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.007662   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...    ...       ...   
442  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000922   
443  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...    0.0  0.000580   
444  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.007223   
445  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.025574   
446  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.081739   
447  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
448  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.041216   
449  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.014122   
450  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.002922   
451  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000502   
452  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000708   
453  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
454  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
455  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.008027   
456  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.117901   
457  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.013684   
458  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.159181   
459  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    0.0  0.000000   
460  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...    1.0  0.041216   
461  0.0  0.0  1.0  0.0  0.0

#splitting the data set into training and testing with 20% of the data for testing

In [32]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

#Creating logistic regression object and doing Feature selection using Recursive feature elimination function

#Using classification report and confusion matrix to test the prediction accuracy

In [74]:
dt=LogisticRegression()
dt=RFE(dt,92,1)
dt.fit(x_train,y_train)
y_p=dt.predict(x_test)
cc= classification_report(y_test,y_p)
cm=confusion_matrix(y_test,y_p)
cm

array([[34, 18],
       [11, 32]])

In [73]:
cc

'             precision    recall  f1-score   support\n\n        0.0       0.70      0.73      0.72        52\n        1.0       0.66      0.63      0.64        43\n\navg / total       0.68      0.68      0.68        95\n'

#Using classification report and confusion matrix to test the prediction accuracy

In [67]:
nn=MLPClassifier()
nn.fit(x_train,y_train)
y_p=nn.predict(x_test)
cm=confusion_matrix(y_test,y_p)
cm

array([[20, 32],
       [ 8, 35]])

#Creating Decision Tree classifier object and doing Feature selection using Recursive feature elimination function

#Using classification report and confusion matrix to test the prediction accuracy

In [70]:
dt= DecisionTreeClassifier()
dt=RFE(dt,92,1)
dt.fit(x_train,y_train)
y_p=dt.predict(x_test)
cm=confusion_matrix(y_test,y_p)
cc= classification_report(y_test,y_p)
cc

'             precision    recall  f1-score   support\n\n        0.0       0.70      0.73      0.72        52\n        1.0       0.66      0.63      0.64        43\n\navg / total       0.68      0.68      0.68        95\n'

In [71]:
cm

array([[38, 14],
       [16, 27]])